version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: shipment_tracker_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: shipment_tracker
    ports:
      - "5432:5432"
      - "5433:5432" # fallback mapping if 5432 is in use
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
